enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules

npmRegistries:
  "https://backstage-dev-501362394160.d.codeartifact.us-east-1.amazonaws.com/npm/backstage-npm/":
    npmAlwaysAuth: true
    npmAuthToken: ""

npmRegistryServer: "https://backstage-dev-501362394160.d.codeartifact.us-east-1.amazonaws.com/npm/backstage-npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
